version: "3.8"

services:
  database:
    image: mysql:8.0.33
    container_name: ${MYSQLDB_HOSTNAME}
    env_file: .env
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    restart: unless-stopped

  app:
    image: car_store
    depends_on:
      - "${MYSQLDB_HOSTNAME}"
    build: .
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://${MYSQLDB_HOSTNAME}:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      JWT_SECRET_VALUE: ${JWT_SECRET_PROD}
      SPRING_SCHEMA_VALUE: ${SPRING_SCHEMA_PROD}
      SPRING_HOST_VALUE: ${SPRING_HOST_PROD}
      STRIPE_SECRET_API_KEY_VALUE: ${STRIPE_SECRET_API_KEY_PROD}
      TELEGRAM_BOT_TOKEN_VALUE: ${TELEGRAM_BOT_TOKEN_PROD}
      TELEGRAM_BOT_USERNAME_VALUE: ${TELEGRAM_BOT_USERNAME_PROD}
      TELEGRAM_BOT_CHAT_ID_VALUE: ${TELEGRAM_BOT_CHAT_ID_PROD}
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    restart: on-failure
